import { unsplash as u } from "@/lib/media";
import { Reveal } from "@/components/motion/Reveal";
import { SectionTitle } from "@/components/ui/SectionTitle";

const items = [["1573496359142-b8d87734a5a2","४० वर्षपछि पनि नयाँ क्षेत्र सिक्नेहरूले के फेरे","उनीहरूले दैनिक सिकाइ समय छुट्याए र सानो प्रयोगबाट सुरु गरे…"],["1522071820081-009f0129c71c","मिटिङ घटाएर पनि प्रभाव बढाउने टोलीको तरिका","निर्णय लग, असिंक अपडेट र स्पष्ट जिम्मेवारीले फरक पार्छ…"],["1517245386807-bb43f82c33c4","प्रमोशनअघि तयार गर्नुपर्ने दस प्रमाण","नतिजा, प्रभाव र सहकार्य — कसरी कागजात बनाउने भन्ने…"]];
/** विचार / ब्लग — Opinion */
export function Vichar() {
 return <section className="spotlight container" id="opinion" aria-labelledby="spotlight-title"><SectionTitle href="/category/vichar"><span id="spotlight-title">विचार / ब्लग</span></SectionTitle><div className="spotlight__grid"><Reveal className="spotlight__lead reveal"><div className="spotlight__lead-bg" aria-hidden="true" /><div className="spotlight__lead-inner"><a className="spotlight__lead-media" href="#article" tabIndex={-1} aria-hidden="true"><img className="img-cover" src={u("1552664730-d307ca884978",800,520)} alt="रातको सिफ्टले करियर रोक्छ भन्ने विश्वास सही हो?" width="800" height="520" loading="lazy" /></a><h3 className="spotlight__lead-title"><a href="#article">रातको सिफ्टले करियर रोक्छ भन्ने विश्वास सही हो?</a></h3><p className="spotlight__lead-excerpt">धेरैले रात्रि सिफ्टलाई वृद्धि रोकने कारक ठान्छन्। प्रबन्धक र अपरेटरहरू भन्छन् — समस्या सिफ्ट होइन, दृश्यता र सिकाइको योजना हो।</p></div></Reveal><Reveal className="spotlight__list reveal reveal-delay-1"><ul>{items.map(([image,title,excerpt]) => <li key={title}><a className="spotlight__item" href="#article"><img src={u(image,200,160)} alt={title} width="100" height="80" loading="lazy" /><span><strong className="line-2">{title}</strong><em className="line-2">{excerpt}</em></span></a></li>)}</ul></Reveal><Reveal className="spotlight__tips reveal reveal-delay-2"><div className="spotlight__fold" aria-hidden="true" /><a className="spotlight__tips-head" href="#article"><span className="spotlight__tips-icon" aria-hidden="true">☞</span>करियर प्लेबुक <i className="fa-solid fa-chevron-right" aria-hidden="true" /></a><div className="spotlight__tips-body"><p>करियर यात्रामा एकपटकमा एउटा स्पष्ट कदम मात्र लिनुहोस्।</p><p>सिकाइ र विश्राम दुवै राख्नुहोस् — थकानले निर्णय बिगार्छ।</p><p>साना लक्ष्य राख्नुहोस्, तर नियमित समीक्षा नछोड्नुहोस्।</p><p>रातमा भारी काम घटाउनुहोस्; दिनको मुख्य घण्टामा गहिरो काम गर्नुहोस्।</p></div></Reveal></div></section>;
}
